<a href="https://colab.research.google.com/github/Nazhan99/Tensorflow_notes/blob/main/00_Tensorflow_fundamental.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#fundamental concepts of tensors using tensorflows

more specifically, we are going to cover:
* Introduction to tensors
* getting info from tensors
* manipulating tensors
* tensors and numpy
* using tf.function
* using GPU with tensorflows
* exercises

#Introduction to Tensors

In [5]:
#Import tensorflow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [10]:
#Create tensors with tf.constant()
scalar=tf.constant(7) #ctrl+shift+space for details attributes
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [11]:
#check the number of dimensions of a tensor
scalar.ndim

0

In [12]:
#create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [13]:
#check the dimension of vector
vector.ndim

1

In [16]:
#create a matrix (has more than 1 dimension)
matrix= tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [17]:
matrix.ndim

2

In [19]:
#create another matrix
another_matrix=tf.constant([[10.,7.],
                            [7.,10.],
                            [2.,2.]], dtype=tf.float16) #specify the data type
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 2.,  2.]], dtype=float16)>

In [20]:
another_matrix.ndim

2

In [23]:
#create a tensor
tensor= tf.constant([[[1,2,3],
                      [4,5,6]],
                      [[7,8,9],
                      [10,11,12]],
                      [[13,14,15],
                      [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [24]:
tensor.ndim

3

what we created so far:

*   scalar: a single number
*   vector: a number with direction
*   matrix: a 2 dimension array of numbers
*tensor: an n-dimension array of number, can be any numebr, a 0-dimensional tensor is a scalar, a 1-dimensioonal tensor is a vector


###create tensor with tf.Variable

In [25]:
#create the same tensor with tf.Variable() as above
changeable_tensor= tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [26]:
#change one of the elements in our changeable tensor
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [27]:
#lets try .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [28]:
#lets try change our unchangeable tensor
unchangeable_tensor[0].assign(7)
unchangeable_tensor

AttributeError: ignored

###Creating random tensor

random tensors are tensors of some abitrary size which contain random numbers.

In [35]:
#create two random but same tensors
random_1=tf.random.Generator.from_seed(7) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(7)
random_2=random_2.normal(shape=(3,2))

#are they equal?
random_1,random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.3240396 ,  0.28785667],
        [-0.8757901 , -0.08857018],
        [ 0.69211644,  0.84215707]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)